import os

print('                                                          ')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('!              Inicializando  PRE_CAMS                   !')
print('!                  Version beta 0.2                      !')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('                                                          ')
print('                                                          ')
print('Creando carpetas...                                       ')
print('                                                          ')
os.system('python3 constructor.py')
print('                                                          ')
print('Carpetas DATA/SALIDAS creadas                             ')
print('                                                          ')
print('                                                          ')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('!            Descargando datos para simulación           !')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('                                                          ')
print('                                                          ')
os.system('python3 data_cams.py')
print('Descarga completa                                         ')
print('                                                          ')
print('                                                          ')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('!                Simulación en proceso                   !')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('                                                          ')
print('                                                          ')
os.system('python3 calculo_velocidad.py')
os.system('python3 predic_tem.py')
os.system('python3 predic_dewpoint.py')
os.system('python3 predic_humedad.py')
os.system('python3 predic_u.py')
os.system('python3 predic_v.py')
os.system('python3 predic_dir.py')
os.system('python3 predic_vel.py')
print('                                                          ')
print('                                                          ')
print('                                                          ')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('!               Predicción terminada                     !')
print('!          Gracias por utilizar PRE_CAMS                 !')
print('!   Dudas/sugerencias/errores: camiloferro07@gmail.com   !')
print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
print('                                                          ')
print('                                                          ')
print('                                                          ')